### ISSUE TITLE
[Trello comments dashboard] Flag already processed items

### ISSUE THREAD

**Issue by colingrodecoeur360** [360Learning/360learning.github.io#17]
# Context

> A nice-to-have would be a system of tracking the items that have been handled (like a todo list).

> Suggestion: the issue I had is highlighting things I did not process yet from the pollution of topics I already tackled. I'm not sure what would be the best solution, maybe the possibility to whitelist and blacklist keywords, or lists and boards. There's also the possibility to flag comments as processed and hide them, but it only works for small amount of comments.

# Spec

Implement buttons to:
- download the filtered comments as a CSV file
- copy the CSV to the clipboard (for easy copy-paste into a Google Sheets)

**Comment by colingrodecoeur360** [comment]
@flavien360 @eripoche Episode 2 of this side project 🎥 

I implemented a CSV export:

<img width="977" alt="image" src="https://user-images.githubusercontent.com/51365591/166145832-bee0a1e7-b5c7-4823-896b-74609ba109e2.png">

Since you were the 2 brave people that gave me detailed feedback, do you want to try it and tell me if it would answer your needs? 

- Clone the repo if you haven't already
- `git fetch`
- `git checkout master-17-export-trello-comments-csv`
- `open trelloCommentsDashboard.html`

(I voluntarily give you minimal instructions for the actual review to see if the workflow is intuitive enough)

**Comment by eripoche** [comment]
@colingrodecoeur360
- Good call leveraging GSheets filtering capabilities and not clutter this tool 🚀 And personally I already write and store the main feedback in GDocs.
- I simulated writing my previous P2P feedback and naturally used the template + copy/paste, and it solves my problem ✅ I tried the CSV export as well, it works too, but doesn't have the header filtering already set from the template, but I don't think you can do much about this. I'm curious which solution will be the most used by other devs.
- Thanks for this improvement 🙏🏻 I'll try it again during the next feedback session.

**Comment by flavien360** [comment]
@colingrodecoeur360 I love the CSV export, this would fill the need for tracking the `done` status. Can I give you feedback after I use it for the next feedback session? 🙂

**Comment by colingrodecoeur360** [comment]
@flavien360 Yes, of course! I'll go ahead with the code review then.

On my side, I used it for a probation review last week and found it convenient.

**Comment by colingrodecoeur360** [comment]
It's deployed
